Repository Knect-Dev/Knect-Dev-Backend, pull requests merged in 2022-02, with the labels that each got.

#17 Add basic file structure
  .eslintignore
  .eslintrc.json
  .github/workflows/javascript-tests.yml
  .gitignore
  LICENSE
  README.md
  __tests__/auth.routes.test.js
  __tests__/company.routes.test.js
  __tests__/error.test.js
  __tests__/job.routes.test.js
  __tests__/logger.test.js
  __tests__/user.routes.test.js
  index.js
  lib/error-handlers/403.js
  lib/error-handlers/404.js
  lib/error-handlers/500.js
  lib/middleware/acl.js
  lib/middleware/basic.js
  lib/middleware/bearer.js
  lib/middleware/logger.js
  lib/models/company.model.js
  lib/models/index.js
  lib/models/job.model.js
  lib/models/user.model.js
  lib/routes/auth.routes.js
  lib/routes/company.routes.js
  lib/routes/index.js
  lib/routes/job.routes.js
  lib/routes/user.routes.js
  lib/server.js
Labels: server

#21 Add DB functionality to routes
  lib/middleware/acl.js
  lib/models/data-collections.js
  lib/models/index.js
  lib/models/user.model.js
  lib/routes/auth.routes.js
  lib/routes/company.routes.js
  lib/routes/index.js
  lib/routes/job.routes.js
  lib/routes/user.routes.js
  lib/server.js
  package-lock.json
Labels: database

#25 Auth execution
  README.md
  lib/middleware/acl.js
  lib/middleware/basic.js
  lib/middleware/bearer.js
  lib/models/data-collections.js
  lib/models/user.model.js
  lib/routes/auth.routes.js
  lib/routes/index.js
Labels: server

#34 Acl
  lib/middleware/acl.js
  lib/middleware/bearer.js
  lib/models/company.model.js
  lib/models/job.model.js
  lib/models/user.model.js
  lib/routes/index.js
Labels: server

#40 Add allowed users to view jobs of others
  lib/models/user.model.js
  lib/routes/index.js
Labels: server

#43 company route testing pass
  __tests__/auth.routes.test.js
  __tests__/company.routes.test.js
  __tests__/error.test.js
  __tests__/job.routes.test.js
  __tests__/logger.test.js
  __tests__/user.routes.test.js
  lib/routes/index.js
Labels: server

#45 Add new user and admin tokens
  __tests__/company.routes.test.js
Labels: server

#49 adds check to make sure an email cannot be registered twice.
  lib/routes/auth.routes.js
Labels: server

#50 modify user tests to work with duplication check
  __tests__/auth.routes.test.js
  __tests__/user.routes.test.js
  lib/middleware/bearer.js
  lib/routes/auth.routes.js
Labels: server

#52 Readme update
  README.md
  img/knect-logo.png
  img/knectdev.PNG
Labels: documentation
